package raftmeta

const (
	CREATE_DATABASE_PATH                       = "/create_database"
	DROP_DATABASE_PATH                         = "/drop_database"
	CREATE_SHARD_GROUP_PATH                    = "/create_shard_group"
	CREATE_DATA_NODE_PATH                      = "/create_data_node"
	DROP_RETENTION_POLICY_PATH                 = "/drop_retention_policy"
	DELETE_DATA_NODE_PATH                      = "/delete_data_node"
	FREEZE_DATA_NODE_PATH                      = "/freeze_data_node"
	CREATE_RETENTION_POLICY_PATH               = "/create_retention_policy"
	UPDATE_RETENTION_POLICY_PATH               = "/update_retention_policy"
	CREATE_USER_PATH                           = "/create_user"
	DROP_USER_PATH                             = "/drop_user"
	UPDATE_USER_PATH                           = "/upate_user"
	SET_PRIVILEGE_PATH                         = "/set_privilege"
	SET_ADMIN_PRIVILEGE                        = "/set_admin_privilege"
	AUTHENTICATE_PATH                          = "/authenticate"
	DROP_SHARD_PATH                            = "/drop_shard"
	TRUNCATE_SHARD_GROUPS_PATH                 = "/truncate_shard_groups"
	PRUNE_SHARD_GROUPS_PATH                    = "/prune_shard_groups"
	DELETE_SHARD_GROUP_PATH                    = "/delete_shard_group"
	PRECREATE_SHARD_GROUPS_PATH                = "/precreate_shard_groups"
	CREATE_DATABASE_WITH_RETENTION_POLICY_PATH = "/create_database_with_policy"
	CREATE_CONTINUOUS_QUERY_PATH               = "/create_continuous_query"
	DROP_CONTINUOUS_QUERY_PATH                 = "/drop_continuous_queyr"
	CREATE_SUBSCRIPTION_PATH                   = "/create_subscription"
	DROP_SUBSCRIPTION_PATH                     = "/drop_subscription"
	DATA_PATH                                  = "/data"
	PING_PATH                                  = "/ping"
	ACQUIRE_LEASE_PATH                         = "/acquire_lease"
	ADD_SHARD_OWNER                            = "/add_shard_owner"
	REMOVE_SHARD_OWNER                         = "/remove_shard_owner"
)
